### PR TITLE
Minor style tweaks to notebook and style updates to example

### PR DESCRIPTION
**Pull request by afshin**
Updating some small notebook styles and updating the example to reflect those changes.

### CODE REVIEW

**Comment by blink1073** [comment]
Screenshot?

**Comment by afshin** [comment]
new version:
new version
old version:
old version

**Comment by blink1073** [comment]
@cameronoelsen, @ellisonbg, any objections?

**Comment by jasongrout** [comment]
I'm playing "spot the differences", and not winning...

Looks good to me.

**Comment by afshin** [comment]
The main thing was moving some margins out of the core widget and into theme so that the widget is more embeddable.

**Comment by jasongrout** [comment]
Great; thanks!

**Pull request merged**
