### PR TITLE
Notebook model tests

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by jasongrout** [comment]
You deleted the WIP, but the tests are not passing. This is still a WIP, right? (just checking...)

**Comment by blink1073** [comment]
Ah, the tests were passing locally, I'll fix it up.

**Comment by blink1073** [comment]
All set, it needed a rebase.

**Comment by jasongrout** [comment]
Thanks. I'm merging this after light review, to keep things moving. I'll be able to look at things more carefully later this week.

**Pull request merged**
