### PR TITLE
WIP Update the notebook to use a provided rendermime instance

### PR DESCRIPTION
**Pull request by jasongrout**
This supersedes #119.

TODO:
- [ ] Change example to create a rendermime instance and pass it in

### CODE REVIEW

**Comment by blink1073** [comment]
@jasongrout, I sent you a PR that finishes this up.

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
@blink1073 - I was getting a typescript build error, and even after I tweaked the example code, I'm still getting:

```
src/index.ts(85,7): error TS2322: Type 'JavascriptRenderer' is not assignable to type 'IRenderer<Widget>'.
  Types of property 'render' are incompatible.
    Type '(mimetype: string, data: string) => Widget' is not assignable to type '(mimetype: string, data: string) => Widget'.
      Type 'Widget' is not assignable to type 'Widget'.
        Types of property 'layout' are incompatible.
          Type 'Layout' is not assignable to type 'Layout'.
            Property 'initialize' is protected but type 'Layout' is not a class derived from 'Layout'.
src/index.ts(89,47): error TS2345: Argument of type 'RenderMime<Widget>' is not assignable to parameter of type 'RenderMime<Widget>'.
  Types have separate declarations of a private property '_renderers'.
```

This is on 

```
$ node --version
v4.2.4
```

**Comment by jasongrout** [comment]
So it looks like there is some error with the deduping. I'm trying to track it down.

**Comment by jasongrout** [comment]
Turns out that we needed to add another dependency to the example package.json.

**Comment by blink1073** [comment]
That is _odd_, there's no reason that should need to be there.

**Comment by blink1073** [comment]
We can readdress after phosphor is squeezed.

**Comment by blink1073** [comment]
Ready to go?

**Comment by jasongrout** [comment]
Yes, we need it because we explicitly import the renderers now.

**Comment by jasongrout** [comment]
anyways, I think this is ready to merge

**Comment by blink1073** [comment]
Great!

**Pull request merged**
