### PR TITLE
Fix `this` reference in serializing functions.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes an error from #56.

### CODE REVIEW

**Comment by blink1073** [comment]
Beat you by 13 seconds.

**Comment by jasongrout** [comment]
grr, and I even had the fix already in my branch!

**Comment by blink1073** [comment]
And, apologies, I generally do test the example before merging, was trying to do too many things at once yesterday.

**Comment by jasongrout** [comment]
You were doing a lot. The merger should have caught it too, though.

**Pull request merged**
