### PR TITLE
Clean up notebook pane and make it a panel

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by jasongrout** [comment]
Why make it a panel? There are built-in assumptions about the children and the model list of cells, and those can easily be violated if notebook is a panel (i.e., if anyone can access the child widget list). I specifically didn't make it a panel so that we could control how child widgets were added.

**Comment by blink1073** [comment]
Because naming is hard.  Maybe we just punt on this until next week.

**Comment by jasongrout** [comment]
My point is not the name. My point is that making the notebook extend Panel rather than Widget exposes to the user functions we don't want the user using (e.g., addChild). I don't care if we call it NotebookPanel or NotebookPane.

**Comment by blink1073** [comment]
Yeah, fair enough, I'll just change the type.

**Comment by blink1073** [comment]
Updated.

**Comment by dwillmer** [comment]
:+1:

**Comment by jasongrout** [comment]
@blink1073 - reading this again, it looks like my concerns were unfounded. My concerns were about the `NotebookWidget` itself (i.e., it should not inherit from Panel).  The `NotebookPanel` is fine to inherit from panel - it's a wrapper around the `NotebookWidget` and there's no assumptions about its children and their order. Sorry for the false alarm.

**Comment by blink1073** [comment]
ha, no worries.

**Pull request merged**
