### PR TITLE
[WIP] Drag n drop

### LINKED ISSUE #152: Add drag and drop behavior for cells

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #152.

Still needs some UX love.

drag-n-drop

### CODE REVIEW

**Comment by blink1073** [comment]
cc @cameronoelsen @ellisonbg, a few things to consider for UX:  

1) What should the drag image look like for a single cell?
2) And for multiple cells?
3) What should the drop target styling look like?

**Comment by ellisonbg** [comment]
Awesome, I will talk with @cameronoelsen about this today

On Tue, Apr 19, 2016 at 9:41 AM, Steven Silvester notifications@github.com
wrote:

> cc @cameronoelsen https://github.com/cameronoelsen @ellisonbg
> https://github.com/ellisonbg, a few things to consider for UX:
> 
> 1) What should the drag image look like for a single cell?
> 2) And for multiple cells?
> 3) What should the drop target styling look like?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/pull/189#issuecomment-212010103

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
This is nifty!

**Comment by jasongrout** [comment]
Please re-open this against https://github.com/jupyter/jupyterlab if it is still applicable.

**Pull request closed without merging**
