### PR TITLE
Incorporate various dependencies into one repo for simplicity.

### PR DESCRIPTION
**Pull request by jasongrout**
This incorporates:

jupyter-js-output-area version 0.3.1
juptyer-js-input-area version 0.0.6
jupyter-js-cells version 0.2.6

### CODE REVIEW

**Comment by blink1073** [comment]
Ready?

**Comment by jasongrout** [comment]
Just about...

**Comment by jasongrout** [comment]
Yep, I think so, @blink1073

**Comment by blink1073** [comment]
Here we go...

**Pull request merged**
