### PR TITLE
Clean up mode handling

### PR DESCRIPTION
**Pull request by blink1073**
Use focus/blur events and an explicit `focus()` method on the editor widget.

### CODE REVIEW

**Comment by blink1073** [comment]
@jasongrout, I'm not so sure the notebook is the right level for mode.  I can see a standalone cell being in edit mode or command mode, and the logic to find the right cell to tag on a focus event is costly. I'd rather move this back down to the cell level but use the focus/blur events.

**Comment by ellisonbg** [comment]
What if we have cell fire a focused signal to avoid the search through the
cells?

On Thu, Mar 17, 2016 at 6:34 AM, Steven Silvester notifications@github.com
wrote:

> @jasongrout https://github.com/jasongrout, I'm not so sure the notebook
> is the right level for mode. I can see a standalone cell being in edit mode
> or command mode, and the logic to find the right cell to tag on a focus
> event is costly. I'd rather move this back down to the cell level but using
> the focus/blur events.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/pull/103#issuecomment-197881116

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
I could add a `focusChanged` signal to `IEditorWidget`.

**Comment by blink1073** [comment]
@ellisonbg, you are also of the opinion that `mode` does not belong on the cell?

**Comment by ellisonbg** [comment]
But cells can become focused by clicking anywhere in the cell as well, so
wouldn't cell itself be the right place for that.

On Thu, Mar 17, 2016 at 8:03 AM, Steven Silvester notifications@github.com
wrote:

> I could add a focusChanged signal to IEditorWidget.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/pull/103#issuecomment-197923190

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
The cell itself gets focused on a click, but the mode is directly linked to the editor focus.

**Comment by ellisonbg** [comment]
Mostly so - it is difficult to imagine why someone would want a single cell
with `mode`. Also, I could imagine that an alternate notebook could have a
very different way of managing keyboard shortcuts and focus but still use
our cells. But I recognize this stuff is really subtle and it may, in the
end, be easier to put in on the cell.

On Thu, Mar 17, 2016 at 8:04 AM, Steven Silvester notifications@github.com
wrote:

> @ellisonbg https://github.com/ellisonbg, you are also of the opinion
> that mode does not belong on the cell?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/pull/103#issuecomment-197923714

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
I still think, theoretically, that the mode is naturally a property of the container, not the cells themselves. I'll look at this and I'm sure I'll have a more concrete opinion.

**Comment by jasongrout** [comment]
Another test is "does a cell need to know its mode?" I think the answer is no.

**Comment by blink1073** [comment]
I'm in the process of moving it up to the notebook level, adding an `editorFocusChanged` signal to the cell widget.

**Comment by jasongrout** [comment]
So the cell would be propagating the signal from the editor? I thought we were going to have the notebook reach in and listen to the editor model directly, or (possibly even better) have the notebook directly listen for focus events that bubbled up from the DOM. I'd like to get away from propagating signals if possible, since it complicates the logic.

**Comment by blink1073** [comment]
The editor wouldn't have a signal, the cell would be listening to the focus event on the editor, and then turning that into a signal so we know _which_ cell was focused.

**Comment by blink1073** [comment]
Otherwise we can go back to 9d401bf and use the `node.contains()` logic again.

**Comment by jasongrout** [comment]
@ellisonbg, @sccolbert pointed out that the browser DOM contains test is fast, so even though the search is a linear search through the cells, as opposed to a direct signal, it is not likely to be a performance problem for notebooks on the order of sizes we're interested in.

**Comment by blink1073** [comment]
Okay, reverting.

**Comment by blink1073** [comment]
Closing in favor of #105.

**Pull request closed without merging**
