### PR TITLE
[WIP] Implement mathjax

### PR DESCRIPTION
**Pull request by blink1073**
Problem:

Providing `webFont: 'STIX-Web',` causes MathJax to load the `mathjax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js` file, even if it has already been evaluated by WebPack.  When rendering, it loads the following files:

```
jax/output/HTML-CSS/fonts/STIX-Web/Main/Italic/Main.js
fonts/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Italic.woff
fonts/HTML-CSS/STIX-Web/otf/STIXMathJax_Main-Italic.otf
```

If the `webFont` is set to `null` and the `fontdata` file is loaded by MathJax, it tries to load the non-existent `jax/output/HTML-CSS/fonts/Main/Italic/Main.js`.  Trying to load an appropriate `Italic/Main` file via WebPack results in an error during page load in `config/TeX-AMS_HTML-full`.

Trying to render the output as SVG tries to load `jax/output/SVG/config.js`.

Note: The `node_modules/mathjax` (2.6.1) folder and the `notebook/static/components/mathjax` (2.6.0) folder are both 58M.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @jasongrout

**Comment by jasongrout** [comment]
Thanks

**Comment by blink1073** [comment]
My recommendation is to use MathJax in a script tag, as it was intended, and use it to render the markdown cells if available, but fall back on a bundled `katex` if it is not available.  Since while `katex` is faster, it is not as fully featured.

**Comment by blink1073** [comment]
cc @minrk

**Comment by jasongrout** [comment]
@blink1073 - that sounds like a good idea to me.  This may help: https://groups.google.com/forum/#!topic/mathjax-users/UT9qMPPwbzg. But I'm fine just including it as a script tag for now, and planning on making things more modular with the mathjax 3.0 rewrite.

**Comment by minrk** [comment]
Script tag makes sense. Thanks for digging into this, @blink1073!

**Comment by blink1073** [comment]
Closing in favor of #57.

**Comment by jasongrout** [comment]
I went ahead and posted a short query to the mathjax-users mailing list: https://groups.google.com/forum/#!topic/mathjax-users/1os6XOGkLOc. I'm really curious if someone has used webpack to bundle mathjax.

**Comment by pkra** [comment]
@jasongrout feel free to cc me on similar issues.

**Pull request closed without merging**
